<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="napiWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/napiWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/napiWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://beeline.ru/napi">
    <import location="config/napi.wsdl" namespace="http://beeline.ru/napi"/>
    <plnk:partnerLinkType name="NAPIEjbBeanLinkType">
        <plnk:role name="NAPIEjbBeanRole" portType="ns:NAPIEjbBean"/>
    </plnk:partnerLinkType>
</definitions>
